version: '2'
services:
 postgres:
   image: postgres:9.6
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_DB=bank_poc_db
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=123456
     - MAX_CONNECTIONS=300
   volumes:
     - ./docker-compose-postgres.sql:/docker-entrypoint-initdb.d/setup.sql